version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=address_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/sql/create_address_schemas.sql:/docker-entrypoint-initdb.d/create_address_schemas.sql
      - ./db/sql/states.sql:/docker-entrypoint-initdb.d/states.sql
      - ./db/sql/zips.sql:/docker-entrypoint-initdb.d/zips.sql
volumes:
  db:
    driver: local