version: '3.8'

name: address-container
services:
  app:
    image: 'quarkus/address-service'
    container_name: "address-app"
    ports:
      - '8080:8080'
    links:
      - "address-db"
    environment:
      - DB_USER=root
      - DB_PWD=root
      - DB_URL=jdbc:mysql://mysql-db/address

  address-db:
    image: mysql:8.0
    container_name: "address-db"
    environment:
      - MYSQL_DATABASE=address
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - address:/var/lib/mysql
      - ./../../../db/sql/create_address_schemas.sql:/docker-entrypoint-initdb.d/create_address_schemas.sql
      - ./../../../db/sql/states.sql:/docker-entrypoint-initdb.d/states.sql
      - ./../../../db/sql/zips.sql:/docker-entrypoint-initdb.d/zips.sql
volumes:
  address:
    driver: local