INSERT INTO state(code, name) values ('AK', 'Alaska');
INSERT INTO state(code, name) values ('AL', 'Alabama');
INSERT INTO state(code, name) values ('AR', 'Arkansas');
INSERT INTO state(code, name) values ('AZ', 'Arizona');
INSERT INTO state(code, name) values ('CA', 'California');
INSERT INTO state(code, name) values ('CO', 'Colorado');
INSERT INTO state(code, name) values ('CT', 'Connecticut');
INSERT INTO state(code, name) values ('DE', 'Delaware');
INSERT INTO state(code, name) values ('FL', 'Florida');
INSERT INTO state(code, name) values ('GA', 'Georgia');
INSERT INTO state(code, name) values ('HI', 'Hawaii');
INSERT INTO state(code, name) values ('IA', 'Iowa');
INSERT INTO state(code, name) values ('ID', 'Idaho');
INSERT INTO state(code, name) values ('IL', 'Illinois');
INSERT INTO state(code, name) values ('IN', 'Indiana');
INSERT INTO state(code, name) values ('KS', 'Kansas');
INSERT INTO state(code, name) values ('KY', 'Kentucky');
INSERT INTO state(code, name) values ('LA', 'Louisiana');
INSERT INTO state(code, name) values ('MA', 'Massachusetts');
INSERT INTO state(code, name) values ('MD', 'Maryland');
INSERT INTO state(code, name) values ('ME', 'Maine');
INSERT INTO state(code, name) values ('MI', 'Michigan');
INSERT INTO state(code, name) values ('MN', 'Minnesota');
INSERT INTO state(code, name) values ('MO', 'Missouri');
INSERT INTO state(code, name) values ('MS', 'Mississippi');
INSERT INTO state(code, name) values ('MT', 'Montana');
INSERT INTO state(code, name) values ('NC', 'North Carolina');
INSERT INTO state(code, name) values ('ND', 'North Dakota');
INSERT INTO state(code, name) values ('NE', 'Nebraska');
INSERT INTO state(code, name) values ('NH', 'New Hampshire');
INSERT INTO state(code, name) values ('NJ', 'New Jersey');
INSERT INTO state(code, name) values ('NM', 'New Mexico');
INSERT INTO state(code, name) values ('NV', 'Nevada');
INSERT INTO state(code, name) values ('NY', 'New York');
INSERT INTO state(code, name) values ('OH', 'Ohio');
INSERT INTO state(code, name) values ('OK', 'Oklahoma');
INSERT INTO state(code, name) values ('OR', 'Oregon');
INSERT INTO state(code, name) values ('PA', 'Pennsylvania');
INSERT INTO state(code, name) values ('RI', 'Rhode Island');
INSERT INTO state(code, name) values ('SC', 'South Carolina');
INSERT INTO state(code, name) values ('SD', 'South Dakota');
INSERT INTO state(code, name) values ('TN', 'Tennessee');
INSERT INTO state(code, name) values ('TX', 'Texas');
INSERT INTO state(code, name) values ('UT', 'Utah');
INSERT INTO state(code, name) values ('VA', 'Virginia');
INSERT INTO state(code, name) values ('VT', 'Vermont');
INSERT INTO state(code, name) values ('WA', 'Washington');
INSERT INTO state(code, name) values ('WI', 'Wisconsin');
INSERT INTO state(code, name) values ('WV', 'West Virginia');
INSERT INTO state(code, name) values ('WY', 'Wyoming');
